"""Stripe

Revision ID: 5da922050da0
Revises: 470ccb300282
Create Date: 2025-05-05 14:49:42.953552

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5da922050da0"
down_revision: Union[str, None] = "470ccb300282"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "stripe_customer_id")
    # ### end Alembic commands ###
