"""Cascade user deletion

Revision ID: e9a99f2b6481
Revises: 5544d870281e
Create Date: 2025-12-14 12:46:09.344315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a99f2b6481'
down_revision: Union[str, None] = '5544d870281e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sync_requests_user_id_fkey'), 'sync_requests', type_='foreignkey')
    op.create_foreign_key(None, 'sync_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_requests', type_='foreignkey')
    op.create_foreign_key(op.f('sync_requests_user_id_fkey'), 'sync_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
