"""Initial schema

Revision ID: 59a02208eaf9
Revises: 
Create Date: 2025-03-29 14:41:48.863235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a02208eaf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('song_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_requests_completed'), 'sync_requests', ['completed'], unique=False)
    op.create_index(op.f('ix_sync_requests_created'), 'sync_requests', ['created'], unique=False)
    op.create_index(op.f('ix_sync_requests_user_id'), 'sync_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_requests_user_id'), table_name='sync_requests')
    op.drop_index(op.f('ix_sync_requests_created'), table_name='sync_requests')
    op.drop_index(op.f('ix_sync_requests_completed'), table_name='sync_requests')
    op.drop_table('sync_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
