"""Stripe

Revision ID: 5da922050da0
Revises: 470ccb300282
Create Date: 2025-05-05 14:49:42.953552

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from common import stripe

# revision identifiers, used by Alembic.
revision: str = "5da922050da0"
down_revision: Union[str, None] = "470ccb300282"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(), nullable=True))

    connection = op.get_bind()
    result = connection.execute(
        sa.text("SELECT id FROM users WHERE stripe_customer_id IS NULL")
    )
    for row in result:
        new_stripe_id = stripe.create_customer()
        connection.execute(
            sa.text(
                "UPDATE users SET stripe_customer_id = :stripe_id WHERE id = :user_id"
            ),
            {"stripe_id": new_stripe_id, "user_id": row.id},
        )

    op.alter_column("users", "stripe_customer_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT stripe_customer_id FROM users"))
    for row in result:
        stripe.delete_customer(row.stripe_customer_id)

    op.drop_column("users", "stripe_customer_id")
    # ### end Alembic commands ###
